# Generated by Django 3.1.2 on 2020-10-27 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_reservation_datetime_begin'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='blackboard',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='multimedia_board',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='number_of_computers',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AdditionalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.room')),
            ],
        ),
    ]
