# Generated by Django 3.1.2 on 2020-10-30 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=100)),
                ('availability_level', models.PositiveIntegerField()),
                ('projector', models.BooleanField()),
                ('multimedia_board', models.BooleanField()),
                ('blackboard', models.BooleanField()),
                ('number_of_places', models.PositiveIntegerField()),
                ('number_of_computers', models.PositiveIntegerField()),
                ('destination', models.CharField(choices=[('ASSEMBLY_HALL', 'Assembly Hall'), ('LECTURE', 'Lecture'), ('PRACTICALS', 'Practicals')], max_length=20)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.floor')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('amount', models.PositiveIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.room')),
            ],
        ),
    ]
