# Generated by Django 3.1.2 on 2020-10-31 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='reservation_slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
