# Generated by Django 3.1.2 on 2020-10-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_reservation_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='reservation_slug',
            new_name='room_slug',
        ),
    ]
