# Generated by Django 3.1.2 on 2020-10-31 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20201031_0216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='sign',
        ),
    ]
