# Generated by Django 3.1.2 on 2020-10-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_sign'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='sign',
            field=models.CharField(default=100, max_length=100),
            preserve_default=False,
        ),
    ]
