# Generated by Django 3.1.2 on 2020-10-31 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_slug', models.SlugField(blank=True, default=None, max_length=100, null=True)),
                ('year_slug', models.SlugField(blank=True, default=None, max_length=100, null=True)),
                ('month_slug', models.SlugField(blank=True, default=None, max_length=100, null=True)),
                ('day_slug', models.SlugField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.DateField()),
                ('datetime_begin', models.DateTimeField(blank=True, default=None, null=True)),
                ('time', models.CharField(choices=[('1', '8:00-10:00'), ('2', '10:00-12:00'), ('3', '12:00-14:00'), ('4', '14:00-16:00'), ('5', '16:00-18:00'), ('6', '18:00-20:00')], max_length=12)),
                ('is_upcoming', models.BooleanField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
