# Generated by Django 3.1.2 on 2020-10-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='day_slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='month_slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='year_slug',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
