# Generated by Django 3.1.2 on 2020-10-31 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20201030_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='slug',
            new_name='room_slug',
        ),
    ]
