# Generated by Django 3.1.2 on 2020-10-31 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0003_auto_20201031_0204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_slug',
            new_name='reservation_slug',
        ),
    ]
